{
 "title": "UNFPA",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "Province",
    "query": "select name_km AS __text, id AS __value  from locations where parent_id is null;"
   },
   {
    "name": "age",
    "label": "Age",
    "query": "< 10 : 0 AND 9, 10 - 14 : 10 AND 14, 15 - 17 : 15 AND 17, 18 - 25 : 18 AND 24, 25 - 30 : 25 AND 30,  > 30 : 31 AND 99"
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": "Male : male, Female : female, LGBT+ : lgbt, Unknown :  unkown"
   },
   {
    "name": "characteristic_id",
    "label": "Profile",
    "query": "select name_km AS __text, id AS __value  from characteristics;"
   }
  ]
 },
 "panels": [
  {
   "title": "ផែនទីអ្នកប្រើប្រាស់កម្មវិធីសុខភាពយុវជន",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH _users AS (\n  SELECT\n    u.*\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY u.id, u.*\n)\n\nSELECT\n  CONCAT(\n    'អ្នកប្រើប្រាស់ក្នុងខេត្ត <b>', l.name_km, '</b> (', count(*), ' នាក់)'\n  ) as popup,\n  l.latitude as latitude,\n  l.longitude as longitude,\n  count(*)::text as tooltip\nFROM _users u\nINNER JOIN locations l ON u.province_id = l.id\nGROUP BY l.name_km, l.latitude, l.longitude;"
    }
   ]
  },
  {
   "title": "សង្ខេបការចូលទស្សនា កម្មវិធីសុខភាពយុវជន",
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM facilities\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ចំនួនសរុបអ្នកប្រើប្រាស់កម្មវិធីសុខភាពយុវជន",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(DISTINCT v.app_user_id)\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)"
    }
   ]
  },
  {
   "title": "ចំនួនសរុបការចូលទស្សនាកម្មវិធី (App visits)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _visits AS (\n  SELECT\n    v.*\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code = 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*\n)\n\nSELECT COUNT(*)\nFROM _visits;\n  "
    }
   ]
  },
  {
   "title": "ចំនួនសរុប App visit  in last week(7 days), month(30 days), quarter(90 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _visits AS (\n  SELECT\n    v.*\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code = 'app_visit'\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*\n),\ncount_in_last_7_day AS (\n  SELECT count(*)\n  FROM _visits\n  WHERE visit_date > current_date - interval '7 days'\n),\ncount_in_last_30_day AS (\n  SELECT count(*)\n  FROM _visits\n  WHERE visit_date > current_date - interval '30 days'\n),\ncount_in_last_90_day AS (\n  SELECT count(*)\n  FROM _visits\n  WHERE visit_date > current_date - interval '90 days'\n)\n\nSELECT\n  concat_ws (\n    ' / ',\n    (select * from count_in_last_7_day),\n    (select * from count_in_last_30_day),\n    (select * from count_in_last_90_day)\n  );\n"
    }
   ]
  },
  {
   "title": "ចំនួនសរុបការចូលទស្សនាទំព័រមុខ (Main category)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _visits AS (\n  SELECT\n    v.*\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code != 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*\n)\n\nSELECT COUNT(*)\nFROM _visits;\n  "
    }
   ]
  },
  {
   "title": "ចំនួនការចូលទស្សនាទំព័រមុខ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _visit_pages AS (\n  SELECT\n    v.*,\n    p.display_name as page_name\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code != 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*, p.display_name\n)\n\nSELECT \n  v.page_name,\n  count(*)\nFROM _visit_pages v\nGROUP BY v.page_name;"
    }
   ]
  },
  {
   "title": "ចំនួនការចូលទស្សនាទំព័រមុខបែងចែកតាមលក្ខណៈសម្បត្តិ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  c.name_km,\n  count(*)\nFROM visits v\nINNER JOIN pages p ON v.page_id = p.id\nINNER JOIN app_users u ON v.app_user_id = u.id\nINNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\nINNER JOIN characteristics c ON ac.characteristic_id = c.id\nWHERE \n  p.parent_id is null\n  AND p.code != 'app_visit'\n  AND $__timeFilter(v.visit_date)\n  AND u.gender in ($gender)\n  AND u.age BETWEEN ${age:raw}\n  AND u.province_id in ($province_id)\n  AND ac.characteristic_id in ($characteristic_id)\nGROUP BY c.name_km"
    }
   ]
  },
  {
   "title": "ចំនួនការចូលទស្សនាទំព័រមុខបែងចែកតាមអាយុ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _visit_ages AS (\n  SELECT\n    v.*,\n    (\n      CASE \n        WHEN age > 30 THEN 'Age > 30'\n        WHEN age > 24 THEN 'Age 25 - 30'\n        WHEN age > 17 THEN 'Age 18 - 24'\n        WHEN age > 14 THEN 'Age 15 - 17'\n        WHEN age > 9 THEN 'Age 10 - 14'\n        ELSE 'Age < 10'\n      END\n    ) as age_range\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code != 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*, u.age\n)\n\nSELECT \n  v.age_range,\n  count(*)\nFROM _visit_ages v\nGROUP BY v.age_range;\n"
    }
   ]
  },
  {
   "title": "ចំនួនការចូលទស្សនាទំព័រមុខបែងចែកតាមភេទ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  gender_km,\n  count(*)\nFROM (\n  SELECT\n    v.*,\n    (\n      CASE \n        WHEN gender = 'male' THEN 'ប្រុស'\n        WHEN gender = 'female' THEN 'ស្រី'\n        WHEN gender = 'lgbt' THEN 'LGBT+'\n        ELSE 'អត់ដឹង'\n      END\n    ) as gender_km,\n    u.gender\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code != 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*, u.gender\n) AS vv\nGROUP BY vv.gender_km"
    }
   ]
  },
  {
   "title": "ចំនួនការចូលទស្សនាទំព័រមុខបែងចែកតាមខែ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH _visit_pages AS (\n  SELECT\n    v.*,\n    p.code as page_code\n  FROM visits v\n  INNER JOIN pages p ON v.page_id = p.id\n  INNER JOIN app_users u ON v.app_user_id = u.id\n  INNER JOIN app_user_characteristics ac ON ac.app_user_id = v.app_user_id\n  INNER JOIN characteristics c ON ac.characteristic_id = c.id\n  WHERE \n    p.parent_id is null\n    AND p.code != 'app_visit'\n    AND $__timeFilter(v.visit_date)\n    AND u.gender in ($gender)\n    AND u.age BETWEEN ${age:raw}\n    AND u.province_id in ($province_id)\n    AND ac.characteristic_id in ($characteristic_id)\n  GROUP BY v.id, v.*, p.code\n)\n\nSELECT \n  DATE_TRUNC('month', v.visit_date) AS visit_to_month,\n  count(case when v.page_code='page_one' then 1 end) AS Page1,\n  count(case when v.page_code='page_two' then 1 end) AS Page2,\n  count(case when v.page_code='page_three' then 1 end) AS Page3,\n  count(case when v.page_code='page_four' then 1 end) AS Page4,\n  count(case when v.page_code='page_five' then 1 end) AS Page5,\n  count(case when v.page_code='page_six' then 1 end) AS Page6,\n  count(case when v.page_code='clinic' then 1 end) AS Clinic,\n  count(case when v.page_code='video' then 1 end) AS Video,\n  count(case when v.page_code='service' then 1 end) AS Service\nFROM _visit_pages v\nGROUP BY DATE_TRUNC('month', v.visit_date);\n"
    }
   ]
  }
 ]
}